github:
  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  true

notifications:
  commits: commits@cassandra.apache.org
  issues: commits@cassandra.apache.org
  pullrequests: commits@cassandra.apache.org
  jira_options: link worklog
